### ISSUE TITLE
Add tourism zones

### ISSUE THREAD

**Issue by olafveerman** [olafveerman/taxis#19]
To: https://github.com/olafveerman/taxis/blob/master/data/concelhos.csv

@hmjbrito Is there an entity in Portugal that has an official classification we can use?

**Comment by hmjbrito** [comment]
I believe that these tourism zones were specifically defined for táxis letra T. They are not related with the "Regiões de Turismo" that promote tourism in different areas of the country.
I would wait for the IMT information to confirm what are the existing tourism zones. I guess that the tourism zones for Táxis letra T are only the ones created in the 80's (Lisboa, Porto and Faro) but the IMT information will confirm this feeling.

If I am correct we'll only need these tourism zones:
1. Zona turística do Porto inclui distritos do Porto, Braga e Viana do Castelo. 
2. Zona turística de Lisboa inclui distritos de Lisboa e Setúbal; 
3. Zona turística de Faro correspondente ao distrito de Faro.

The available information states that the contingente (maximum number of táxis letra T) is:
- 20 unidades na zona turística do Porto
- 100 unidades na zona turística de Lisboa
- 80 unidades na zona turística de Faro. 

The law/regulation states that the contingente definition should consider:
"o número de dormidas, o índice de ocupação de estabelecimentos hoteleiros e outros elementos determinantes da procura, como a ocorrência frequente de congressos". It also says that the contingentes should be updated/revaluated every two years but I also guess that no changes were introduced since the 80's. Let's see what the IMT information will say.

**Comment by olafveerman** [comment]
Taxis letra A & T will not be included at this stage.
