### ISSUE TITLE
Include dormidas

### ISSUE THREAD

**Issue by olafveerman** [olafveerman/taxis#47]
It is not possible to aggregate dormidas by NUT.

Instead, include:

- national level json
- mil dormidas for each concelho that has data for 2006 - 2016

**Comment by olafveerman** [comment]
Todo:

- [ ] add national values from INE
- [ ] don't back-fill data
- [ ] don't aggregate data by NUT

**Comment by danielfdsilva** [comment]
@olafveerman Instead of having the dormidas in a separate file, could we have it in the `national.js`, right after results?

```
{
  "meta": {
    "name": "observatorio-taxis-data",
    "description": "Data about taxis in Portugal from 2006 on, aggregated by NUT3 and concelho",
    "source": {
      "name": "Autoridade da Mobilidade e dos Transportes",
      "web": "http://www.amt-autoridade.pt"
    },
    "license": "CC-BY-4.0"
  },
  results: [...],
  dormidas: [...]
}
```

**Comment by olafveerman** [comment]
@danielfdsilva 
I'd prefer not to have data outside of the `results` array. If you can't load it from the other file, could I add the national domidas data in the `results` array?

**Comment by danielfdsilva** [comment]
At this state I'd rather not have to load another file. If you add it to
the results array, how would that be since the results are basically nuts?

On Apr 13, 2017 03:34, "Olaf Veerman" <notifications@github.com> wrote:

@danielfdsilva <https://github.com/danielfdsilva>
I'd prefer not to have data outside of the results array. If you can't load
it from the other file, could I add the national domidas data in the results
array?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/olafveerman/taxis/issues/47#issuecomment-293760504>,
or mute
the thread

**Comment by olafveerman** [comment]
The results are administrative areas, all of which happen to be NUTS3 right
now. I realize the object with national data wouldn't contain the same
indicators, but I'd rather have the exception there, than create a
`dormidas` object outside of the `results` array.

**Comment by olafveerman** [comment]
Implemented.
